### PR TITLE
local.conf / remove WKS-file hack for UZ

### PR DESCRIPTION
**Pull request by JanneKiiskila**
The UZ target will get fixed by PR https://github.com/PelionIoT/meta-pelion-edge/pull/288,
so that we will not need this change in the local.conf.

### CODE REVIEW

**Review by petedyerarm — APPROVED** [review]
LGTM

**Review by ygoyal18 — APPROVED** [review]
LGTM

**Review by esajaa — APPROVED** [review]
Great to see this one fixed!

**Comment by kivaisan** [comment]
Could we get this merged? Just spent some quality time wondering why this target didn't build ;)

**Comment by JanneKiiskila** [comment]
Ah, there is/was dependency on this PR and the other one - they should have both been merged in at the same time!

**Comment by petedyerarm** [comment]
should this have gone into master or dev ?

**Comment by JanneKiiskila** [comment]
Dev of course, oh man. :-/

**Comment by JanneKiiskila** [comment]
https://github.com/PelionIoT/manifest-lmp-pelion-edge/pull/28 - does it dev then.

**Pull request merged**
